### ISSUE TITLE
gatttool is deprecated

### ISSUE THREAD

**Issue by Schnehe** [etobi/bt2mqtt-scripts#1]
Dear etobi,
I really like your project and would like to run it on my Hassio operation system directly and avoid the additional Raspberry Zero. Distance to the IBT-2X is not a problem.
My problem is that Gatttool is deprecated and so your code is not working for me within Hassio using latest bluepy.
Within the rather closed Hassio, I can not install Gatttool using side loads and need an alternative using latest bluepy packages.
Do you have an updated code already or an idea what direction I should look for to adjust your code?
Unluckily I have some basic knowledge in programming, but no experience with shell commands or Python and can't help myself.
Thanks upfront.

**Comment by etobi** [comment]
Hej,
sorry for the late answer. I'm happy to hear you like the project and I'm sorry to say I'm currently not actively using it myself.
For me an dedicated ESP32 near the outdoor kitchen, instead of running a Pi for this (with all the hassle with OS-Updates etc) does a much more stable job while being easier to maintain at the same time.
I'm using https://github.com/runningtoy/InkBird_BLE2MQTT maybe thats something for you, too.

kind regards
   tobias

**Comment by Schnehe** [comment]
Thanks for your feedback.
I was really interessted to have a solution implemented into Home Assistant, but finally also used the InkBird_BLE2MQTT with an ESP32 solution.
